baseurl = "http://doomsparkle.com/"
languageCode = "en-us"
title = "Doom Sparkle"
theme = "doomsparkle"
SectionPagesMenu = "main"
Paginate = 1
PaginatePath = "p"
googleAnalytics = "UA-514101-29"
pluralizeListTitles = false

[[menu.main]]
    name = "members"
    identifier = "members"
    url = "/members/"
    "weight" = 95

[[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about/"
    "weight" = 100
